import { Chivo_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import LaptopNav from "@/components/nav/LaptopNav";
import Footer from "@/components/Footer";

const chivoMono = Chivo_Mono({
  variable: "--font-chivo-mono",
  subsets: ["latin"],
});

const twkLausanne = localFont({
  src: "../fonts/TWKLausanne-550.woff",
  variable: "--font-twk-lausanne",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${chivoMono.variable} ${twkLausanne.variable} antialiased font-twk w-full overflow-x-hidden`}
      >
        <LaptopNav />
        <main className="h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
